version: '2'
services:
  history:
    build: ./docker/history
    environment:
      steemnode: "http://45.79.206.79:8090"
    links:
      - mongo
    volumes:
      - ./docker/history:/src
  # live:
  #   build: ./docker/live
  #   environment:
  #     steemnode: "steemd.steemit.com"
  #   # links:
  #   #   - mongo
  #   ports:
  #     - "8888:8888"
  # sync:
  #   build: ./docker/sync
  #   environment:
  #     steemnode: "http://45.79.206.79:8090"
  #   links:
  #     - mongo
  # witnesses:
  #   build: ./docker/witnesses
  #   environment:
  #     steemnode: "http://45.79.206.79:8090"
  #   links:
  #     - mongo
  # development:
  #   build: ./docker/development
  #   links:
  #     - mongo
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - "80:80"
  mongodata:
    image: mongo:3.3.10
    volumes:
      - /data/db
    command: --break-mongo
  mongo:
    image: mongo:3.3.10
    volumes_from:
      - mongodata
    # ports:
    #   - "27020:27017"
    command: --smallfiles --rest
